---
title: "Weekly Assignment 3"
output: html_document
date: "2023-01-26"
---
[Figure A3](https://www.journals.uchicago.edu/doi/10.1086/704102)
```{r}
# 1. Go to Dryad to choose a published paper and data set and reconstruct your own figure. Code a ggplot graph that looks as close to the published figure as you can.

library(tidyverse)
lobster <-read.table(file="Data/doi_10-4/IsolationByDistance.csv", header=TRUE, sep=",", stringsAsFactors = TRUE)
glimpse(lobster)

```
```{r}
library(ggthemes)
#kpet getting error
#p<- ggplot(data = lobster, aes(x = dist, +   
 # geom_point(aes(y = sample1), color = "red", size=1) +
 # geom_point(aes(y = sample2), color= "blue", size=1)) +
 #   geom_point(color="black", size =1) +
 # ylab("Fst") + 
 # xlab("geographic distance (km)") + 
 #   geom_smooth(method = "lm", se=FALSE, color="black", linetype = "dashed")
  

#p
    
```

```{r}
#b <- ggplot(data = lobster, aes(x = dist, y= cols(c(sample1, sample2)))) +
 # geom_point() +
 # ylab("Fst") + 
 # xlab("geographic distance (km)") +
#geom_smooth(method = "lm", se=FALSE, color="black", linetype = "dashed") +
 # theme_classic()

#b
```

